runtime: nodejs
env: flex
automatic_scaling:
  max_num_instances: 1
  cpu_utilization:
    target_utilization: 0.5

env_variables:
  NODE_ENV: production
  DB_PROD_USER: YOUR_SQL_USER
  DB_PROD_PASSWORD: YOUR_SQL_PASSWORD
  DB_PROD_NAME: YOUR_SQL_DATABASE
  INSTANCE_CONNECTION_NAME: YOUR_INSTANCE_CONNECTION_NAME

beta_settings:
  cloud_sql_instances: YOUR_INSTANCE_CONNECTION_NAME
