runtime: nodejs
env: flex
automatic_scaling:
  max_num_instances: 1
  cpu_utilization:
    target_utilization: 0.5

env_variables:
  NODE_ENV: production

beta_settings:
  cloud_sql_instances: hop-production-195003:us-east4:hop-databases
